apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "operator-os.fullname" . }}-config
  labels:
    {{- include "operator-os.labels" . | nindent 4 }}
data:
  OPERATOR_LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  OPERATOR_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  OPERATOR_HEALTH_HOST: {{ .Values.config.healthHost | quote }}
  OPERATOR_HEALTH_PORT: {{ .Values.config.healthPort | quote }}
  {{- if .Values.nats.enabled }}
  OPERATOR_NATS_URL: {{ .Values.nats.url | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  OPERATOR_REDIS_URL: {{ .Values.redis.url | quote }}
  {{- end }}
  {{- if .Values.worker.enabled }}
  OPERATOR_WORKER_CONCURRENCY: {{ .Values.worker.concurrency | quote }}
  OPERATOR_WORKER_PROCESS_TIMEOUT: {{ .Values.worker.processTimeout | quote }}
  OPERATOR_WORKER_MAX_RETRIES: {{ .Values.worker.maxRetries | quote }}
  {{- end }}
