CREATE TABLE IF NOT EXISTS rate_limits (
    user_id    TEXT PRIMARY KEY,
    tier       TEXT NOT NULL DEFAULT 'free',
    tokens     REAL NOT NULL DEFAULT 0,
    last_time  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    day_count  INTEGER NOT NULL DEFAULT 0,
    day_start  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
